# name: deploy-container

# on: 
#   push:
#     branches:
#       - master
#     paths:
#       - 'container/**'

# defaults:
#   run:
#     working-directory: container

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: action/checkout@v2
#       - run: npm install
#       - run: npm run build

#       - uses: shinyinc/action-aws-cli@v1.2
#       - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
#         env: 
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - 'container/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: container

      - name: Build
        run: npm run build
        working-directory: container

      - name: Upload to AWS S3
        uses: actions/upload-artifact@v2
        with:
          name: container-dist
          path: container/dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: YOUR_AWS_REGION

      - name: Sync to S3
        run: aws s3 sync container/dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest

